# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-08 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.IntegerField()),
                ('times', models.TextField()),
                ('testcaseonbtnlogin', models.IntegerField()),
                ('testcaselogin', models.IntegerField()),
                ('testcasesendnoattach', models.IntegerField()),
                ('testcasesendattach', models.IntegerField()),
                ('testcasefwdsend', models.IntegerField()),
                ('testcaseforward', models.IntegerField()),
                ('testcasereply', models.IntegerField()),
                ('testdownfile', models.IntegerField()),
                ('testcasecheckaddresslist', models.IntegerField()),
                ('testcaseselected', models.IntegerField()),
                ('testcasepush', models.IntegerField()),
                ('testcasecalendar', models.IntegerField()),
                ('testcasediscover', models.IntegerField()),
                ('testcasepersionmessages', models.IntegerField()),
                ('testcaseskydrive', models.IntegerField()),
            ],
        ),
    ]
