# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-08 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='kid',
        ),
    ]
